version: '3.9'
services:
  api:
    build: .
    command: ./execute.sh
    ports:
      - "8000:8000"
    restart: on-failure
    volumes:
      - .:/app
    links:
      - "mysql"
  mysql:
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=funnyfactsdb
      - MYSQL_ROOT_PASSWORD=Qwerty1234